services:
  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    # Esto monta una carpeta de tu disco D: (o C:) dentro del contenedor
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    restart: always

  odoo:
    image: odoo:16
    container_name: odoo_server
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo
    command: >
      odoo -c /etc/odoo/odoo.conf
      --log-level=info
      --log-handler=odoo.addons.sale_trade_in:DEBUG
    # (Opcional) Si quieres persistir algo de Odoo (archivos, logs, etc.)
    volumes:
      - "./odoo_data:/var/lib/odoo"
      - "./custom_addons:/mnt/extra-addons"
    restart: always
